### ISSUE TITLE
Calendar API problems

### ISSUE THREAD

**Issue by atotic** [GoogleWebComponents/google-calendar#18]
I've ported this from Polymer 0.5 to 1.0, and was never unable to get the API to work reliably. Signing in and out would cause gapi errors in `google-calendar-list`, and I never got `google-calendar-busy-now` to work correctly. 

I suspect the problem is client library, and its interaction with the way we load libraries. This bug is just a remainter that this code remains alpha-quality

**Comment by maxrabin** [comment]
On the demo site, https://googlewebcomponents.github.io/, I tried the calendar demo and it doesn't list my calendars. After authenticating it just says "My Calendars" and shows none of them.

**Comment by atotic** [comment]
I see a whole lot of 403s when I try the demo.

**Comment by oPorks** [comment]
Stills intermitente, sometimes work. Do anyone have a clue?
