### ISSUE TITLE
Tests are not runnable because not up to date

### ISSUE THREAD

**Issue by LM450N** [GoogleWebComponents/google-calendar#19]
Before the tests can be run, we have to fix 3 issues.
- rename the folder `tests` into `test`
- add `webcomponent-lite.js` into the [test/index.html](https://github.com/GoogleWebComponents/google-calendar/blob/master/tests/index.html#L7)
- replace `webcomponentsjs.min.js` by `webcomponent-lite.js` into the [test/google-calendar-list-basic.html](https://github.com/GoogleWebComponents/google-calendar/blob/master/tests/google-calendar-list-basic.html#L8)

At this point, we have to update the tests. Notice that Firefox doesn't really like the variable _this_ [here](https://github.com/GoogleWebComponents/google-calendar/blob/master/tests/google-calendar-list-basic.html#L48).

**Comment by masonlouchart** [comment]
This issue is fairly old and there hasn't been much activity on it. ⌛
